"""Add missing columns to orders table

Revision ID: 0598d10698f9
Revises: a5cbf12181a2
Create Date: 2026-06-19 17:41:39.762014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0598d10698f9'
down_revision: Union[str, Sequence[str], None] = 'a5cbf12181a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('client_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('destination', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('payload_type', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('distance', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('dss_decision', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('reason', sa.String(length=255), nullable=True))
    op.drop_column('orders', 'customer_name')
    op.drop_column('orders', 'delivery_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_address', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('orders', sa.Column('customer_name', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('orders', 'reason')
    op.drop_column('orders', 'dss_decision')
    op.drop_column('orders', 'risk_score')
    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'distance')
    op.drop_column('orders', 'payload_type')
    op.drop_column('orders', 'destination')
    op.drop_column('orders', 'client_name')
    # ### end Alembic commands ###
