"""extend_drones_and_add_admin_state

Revision ID: 4ec4cd67d252
Revises: 54a8084d8347
Create Date: 2026-06-20 00:53:41.581843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ec4cd67d252'
down_revision: Union[str, Sequence[str], None] = '54a8084d8347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_admin_state_id'), 'admin_state', ['id'], unique=False)
    op.add_column('drones', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('drones', sa.Column('max_payload', sa.Float(), nullable=True))
    op.add_column('drones', sa.Column('current_payload', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drones', 'current_payload')
    op.drop_column('drones', 'max_payload')
    op.drop_column('drones', 'location')
    op.drop_index(op.f('ix_admin_state_id'), table_name='admin_state')
    op.drop_table('admin_state')
    # ### end Alembic commands ###
